name: CI

on:
  push:
    branches: [ main ]
    paths: [ src, include, test, CMakeLists.txt, conanfile.txt ]
  pull_request:
    branches: [ main ]
    paths: [ src, include, test, CMakeLists.txt, conanfile.txt ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: [ windows-2019, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2 
    - uses: Minimonium/conan-request-action@master

    - name: Configure Conan
      run: |
          pip install conan --upgrade
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Configure CMake
      run: | 
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}
      run: ./bin/unitTests
      
